// Generates public/llms.txt following the llmstxt.org convention:
// H1 site name, a blockquote summary, then H2 sections listing pages as
// markdown links with one-line descriptions.
//
// Source of truth for page titles/descriptions is the actual .mdx content
// (first H1 + first paragraph). Source of truth for grouping/section titles
// and for excluding hidden/WIP pages is app/_meta.global.tsx (the sidebar),
// via scripts/lib/docsMeta.mjs. Legal/regulatory content is excluded on
// purpose (out of scope for an LLM-facing index).
//
// Each page links to its per-page markdown mirror (generated by
// scripts/generateMarkdownPages.mjs, which runs right after this script in
// postbuild) instead of the HTML page, per the llmstxt.org convention of
// pointing at clean markdown.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import {
  ROOT,
  isExcludedDir,
  isHidden,
  sectionFor,
  findMdxFiles,
  frontmatterTitle,
  stripFrontmatter,
  toRoute,
  loadSiteUrl,
} from "./lib/docsMeta.mjs";

const OUT_FILE = path.join(ROOT, "public", "llms.txt");

const SITE_NAME = "Velocity Protocol";
const SITE_SUMMARY =
  "Velocity is a decentralized, cross-margined perpetuals and spot trading protocol on Solana. These docs cover how to use the protocol, how it works under the hood, and how to build on it.";

const siteUrl = loadSiteUrl();

// Turn "[**Perpetual Futures**](/protocol/trading)" style markdown into
// plain text for a one-line description.
function toPlainText(line) {
  return line
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, "") // JSX comments, e.g. {/* HIDDEN: ... */}
    .replace(/\{\/[\s\S]*$/, "") // an unterminated JSX comment opener
    .replace(/`{1,3}([^`]*)`{1,3}/g, "$1")
    .replace(/\*\*([^*]*)\*\*/g, "$1")
    .replace(/\*([^*]*)\*/g, "$1")
    .replace(/_([^_]*)_/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/<[^>]*>/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function extractTitleAndDescription(raw) {
  const text = stripFrontmatter(raw);
  const lines = text.split(/\r?\n/);

  // Titles live in frontmatter since the Fumadocs migration; fall back to a
  // leading H1 for any page that still carries one.
  let title = frontmatterTitle(raw);
  let titleIdx = -1;
  if (title) {
    title = toPlainText(title);
  } else {
    for (let i = 0; i < lines.length; i++) {
      const m = lines[i].match(/^#\s+(.+?)\s*$/);
      if (m) { title = toPlainText(m[1]); titleIdx = i; break; }
    }
  }
  if (!title) return null;

  let description = "";
  for (let i = titleIdx + 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === "") continue;
    if (line.startsWith("#")) break; // hit the next heading, no paragraph found
    if (line.startsWith("import ") || line.startsWith("<") || line.startsWith("export ")) {
      continue;
    }
    // Collect the paragraph (until a blank line or a JSX/heading boundary).
    const paragraph = [];
    let j = i;
    for (; j < lines.length; j++) {
      const l = lines[j];
      if (l.trim() === "") break;
      if (l.trim().startsWith("<") || l.trim().startsWith("#")) break;
      paragraph.push(l.trim());
    }
    const candidate = toPlainText(paragraph.join(" "));
    if (candidate) {
      description = candidate;
      break;
    }
    i = j; // paragraph stripped to nothing (e.g. a JSX comment) - try the next one
  }

  if (description.length > 220) {
    const cut = description.slice(0, 220);
    const lastSpace = cut.lastIndexOf(" ");
    description = `${cut.slice(0, lastSpace)}...`;
  }

  return { title, description };
}

const files = findMdxFiles().sort();
const sections = new Map(); // sectionTitle -> [{route, title, description}]

for (const file of files) {
  const { relPath, route } = toRoute(file);

  if (isExcludedDir(relPath)) continue;
  if (isHidden(relPath)) continue;

  const raw = readFileSync(file, "utf8");
  const parsed = extractTitleAndDescription(raw);
  if (!parsed) continue; // no H1 found, skip rather than guess

  const section = sectionFor(relPath);
  if (!sections.has(section)) sections.set(section, []);
  sections.get(section).push({
    route,
    title: parsed.title,
    description: parsed.description,
  });
}

// --- Render llms.txt ---------------------------------------------------------
const lines = [`# ${SITE_NAME}`, "", `> ${SITE_SUMMARY}`, ""];

for (const [section, pages] of sections) {
  lines.push(`## ${section}`);
  for (const page of pages.sort((a, b) => a.route.localeCompare(b.route))) {
    const url = `${siteUrl}${page.route}.md`;
    const desc = page.description ? `: ${page.description}` : "";
    lines.push(`- [${page.title}](${url})${desc}`);
  }
  lines.push("");
}

if (!existsSync(path.join(ROOT, "public"))) {
  mkdirSync(path.join(ROOT, "public"), { recursive: true });
}
writeFileSync(OUT_FILE, `${lines.join("\n").trimEnd()}\n`, "utf8");

const pageCount = [...sections.values()].reduce((n, arr) => n + arr.length, 0);
console.log(`llms.txt: wrote ${pageCount} pages across ${sections.size} sections to ${path.relative(ROOT, OUT_FILE)}`);
